// Idempotent database seed.
//
// - Creates the Administrator role and baseline programs.
// - Creates the bootstrap admin user ONLY if it does not already exist.
//   On upgrades (admin present) it changes nothing — credentials are never
//   reset by the seed. The initial password comes from ADMIN_INITIAL_PASSWORD
//   (generated by the installer) and the admin must change it on first login.

import { hash } from '@node-rs/argon2';
import { PrismaClient } from '../generated/client/index.js';

const prisma = new PrismaClient();

const BASELINE_PROGRAMS = [
  { key: 'dashboard', name: 'Dashboard', folder: 'File' },
  { key: 'admin.users', name: 'User Administration', folder: 'Administration' },
  { key: 'admin.roles', name: 'Role Administration', folder: 'Administration' },
  { key: 'admin.securedItems', name: 'Secured Items', folder: 'Administration' },
  { key: 'admin.audit', name: 'Audit Log', folder: 'Administration' },
  { key: 'admin.sessions', name: 'Active Sessions', folder: 'Administration' },
];

async function main() {
  const adminEmail = process.env.ADMIN_EMAIL ?? 'admin@erp1.local';
  const adminPassword = process.env.ADMIN_INITIAL_PASSWORD;

  // Administrator role (system role — cannot be deleted via UI).
  const adminRole = await prisma.role.upsert({
    where: { code: 'ADMIN' },
    update: {},
    create: {
      code: 'ADMIN',
      name: 'Administrator',
      description: 'Full system access',
      isSystem: true,
    },
  });

  // Baseline programs, all granted to Administrator.
  for (const p of BASELINE_PROGRAMS) {
    const prog = await prisma.program.upsert({
      where: { key: p.key },
      update: { name: p.name, folder: p.folder },
      create: p,
    });
    await prisma.roleProgram.upsert({
      where: { roleId_programId: { roleId: adminRole.id, programId: prog.id } },
      update: { allow: true },
      create: { roleId: adminRole.id, programId: prog.id, allow: true },
    });
  }

  // Bootstrap admin user — create only if missing.
  const existing = await prisma.user.findUnique({ where: { email: adminEmail } });
  if (existing) {
    console.log(`[seed] Admin already exists (${adminEmail}); leaving unchanged.`);
    return;
  }

  if (!adminPassword) {
    throw new Error(
      '[seed] ADMIN_INITIAL_PASSWORD is not set; cannot create the bootstrap admin. ' +
        'The installer normally provides this.',
    );
  }

  const passwordHash = await hash(adminPassword, {
    // OWASP-recommended Argon2id parameters.
    memoryCost: 19456,
    timeCost: 2,
    parallelism: 1,
  });

  const admin = await prisma.user.create({
    data: {
      email: adminEmail,
      username: 'admin',
      displayName: 'Administrator',
      status: 'ACTIVE',
      passwordHash,
      mustChangePassword: true,
      roles: { create: { roleId: adminRole.id } },
    },
  });

  console.log(`[seed] Created bootstrap admin: ${admin.email} (must change password on first login).`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (err) => {
    console.error(err);
    await prisma.$disconnect();
    process.exit(1);
  });
