// Idempotent database seed.
//
// - Creates the Administrator role and baseline programs.
// - Creates the bootstrap admin user ONLY if it does not already exist.
//   On upgrades (admin present) it changes nothing — credentials are never
//   reset by the seed. The initial password comes from ADMIN_INITIAL_PASSWORD
//   (generated by the installer) and the admin must change it on first login.

import { hash } from '@node-rs/argon2';
import { PrismaClient } from '../generated/client/index.js';

const prisma = new PrismaClient();

const BASELINE_PROGRAMS = [
  { key: 'dashboard', name: 'Dashboard', folder: 'File' },
  { key: 'admin.users', name: 'User Administration', folder: 'Administration' },
  { key: 'admin.roles', name: 'Role Administration', folder: 'Administration' },
  { key: 'admin.approvalPolicies', name: 'Approval Policies', folder: 'Administration' },
  { key: 'admin.securedItems', name: 'Secured Items', folder: 'Administration' },
  { key: 'admin.audit', name: 'Audit Log', folder: 'Administration' },
  { key: 'admin.sessions', name: 'Active Sessions', folder: 'Administration' },
  { key: 'master.entities', name: 'Entities', folder: 'Master Tables' },
  { key: 'master.items', name: 'Items', folder: 'Master Tables' },
  { key: 'master.units', name: 'Units', folder: 'Master Tables' },
  { key: 'recipe.manager', name: 'Recipe Manager', folder: 'Master Tables/Recipe Manager' },
  { key: 'recipe.editor', name: 'Recipe Editor', folder: 'Master Tables/Recipe Manager' },
  { key: 'orders.browser', name: 'Order Browser', folder: 'Transactions/Orders' },
  { key: 'orders.create', name: 'Create Order', folder: 'Transactions/Orders' },
  { key: 'orders.edit', name: 'Edit Order', folder: 'Transactions/Orders' },
  { key: 'orders.revise', name: 'Order Edit (Revisions)', folder: 'Transactions/Orders' },
  { key: 'orders.release', name: 'Release Order', folder: 'Transactions/Orders' },
  { key: 'orders.complete', name: 'Complete Order', folder: 'Transactions/Orders' },
  { key: 'orders.close', name: 'Close Order', folder: 'Transactions/Orders' },
  { key: 'orders.reverse', name: 'Reverse Order Completion', folder: 'Transactions/Orders' },
  { key: 'orders.consume', name: 'Record Consumed Lots', folder: 'Transactions/Orders' },
  { key: 'orders.execute', name: 'Batch Execution', folder: 'Transactions/Orders' },
  { key: 'orders.variance', name: 'Material Variance', folder: 'Transactions/Orders' },
  { key: 'orders.ship', name: 'Record Shipped Lots', folder: 'Transactions/Orders' },
  { key: 'sales.invoices', name: 'Invoices', folder: 'Transactions/Sales' },
  { key: 'sales.shipments', name: 'Packing Slips', folder: 'Transactions/Sales' },
  { key: 'shipping.create', name: 'Create Shipping Order', folder: 'Transactions/Sales' },
  { key: 'shipping.stage', name: 'Shipping Assembly (Stage/Reserve)', folder: 'Transactions/Sales' },
  { key: 'sales.priceLists', name: 'Sales Price Lists', folder: 'Master Tables/Pricing' },
  { key: 'sales.priceListEditor', name: 'Edit Sales Price Lists', folder: 'Master Tables/Pricing' },
  { key: 'sales.bills', name: 'Supplier Bills', folder: 'Transactions/Purchasing' },
  { key: 'purchasing.po', name: 'Purchase Orders', folder: 'Transactions/Purchasing' },
  { key: 'purchasing.create', name: 'Create Purchase Order', folder: 'Transactions/Purchasing' },
  { key: 'purchasing.receive', name: 'Receive Purchase Order', folder: 'Transactions/Purchasing' },
  { key: 'purchasing.priceDetails', name: 'Purchase Price Details', folder: 'Transactions/Purchasing' },
  { key: 'purchasing.priceVersions', name: 'Supplier Price Versions', folder: 'Master Tables/Pricing' },
  { key: 'purchasing.priceVersionEditor', name: 'Edit Supplier Price Versions', folder: 'Master Tables/Pricing' },
  { key: 'qa.cofa', name: 'Certificates of Analysis', folder: 'Quality' },
  { key: 'qa.disposition', name: 'QA Disposition', folder: 'Quality' },
  { key: 'qa.results', name: 'Enter Test Results', folder: 'Quality' },
  { key: 'qa.itemTests', name: 'Item Test Requirements', folder: 'Quality' },
  { key: 'qa.itemTestsEdit', name: 'Edit Item Test Requirements', folder: 'Quality' },
  { key: 'qa.testCatalogEdit', name: 'Edit Test Catalog', folder: 'Quality' },
  { key: 'inventory.browser', name: 'Inventory Browser', folder: 'Transactions/Inventory' },
  { key: 'inventory.adjust', name: 'Inventory Adjustment', folder: 'Transactions/Inventory' },
  { key: 'inventory.transfer', name: 'Inventory Transfer', folder: 'Transactions/Inventory' },
  { key: 'inventory.reverse', name: 'Reverse Receipt', folder: 'Transactions/Inventory' },
  { key: 'inventory.receipts', name: 'Miscellaneous Receipts', folder: 'Transactions/Inventory' },
  { key: 'inventory.count', name: 'Inventory Counts', folder: 'Transactions/Inventory' },
  { key: 'inventory.lotTracking', name: 'Lot Tracking', folder: 'Transactions/Inventory' },
  { key: 'inventory.trace', name: 'Trace Genealogy', folder: 'Transactions/Inventory' },
  { key: 'inventory.recall', name: 'Recall', folder: 'Transactions/Inventory' },
  { key: 'planning.trace', name: 'Plan Tracing', folder: 'Planning' },
  { key: 'planning.short', name: 'Short Inventory', folder: 'Planning' },
  { key: 'planning.recalculate', name: 'Recalculate Plan Trace', folder: 'Planning' },
  { key: 'planning.createPo', name: 'Create PO from Plan', folder: 'Planning' },
  { key: 'planning.supplyDemand', name: 'Inventory Supply & Demand', folder: 'Planning' },
  { key: 'admin.import', name: 'Legacy Import', folder: 'Administration' },
  { key: 'admin.config', name: 'Configuration', folder: 'Administration' },
  { key: 'accounting.config', name: 'Accounting Masters', folder: 'Master Tables/Accounting' },
  { key: 'accounting.export', name: 'Accounting Export', folder: 'Master Tables/Accounting' },
  { key: 'sales.invoice', name: 'Generate Invoice', folder: 'Transactions/Sales' },
  { key: 'notifications.config', name: 'Notification Update', folder: 'Administration' },
  // §18 set viewers — one program per viewer, mirroring legacy security.
  { key: 'viewers.shipmentDetail', name: 'Shipment Detail Viewer', folder: 'Viewers' },
  { key: 'viewers.openShippingOrderDetail', name: 'Open Shipping Order Detail Viewer', folder: 'Viewers' },
  { key: 'viewers.openMfOrderDetail', name: 'Open MF Order Detail Viewer', folder: 'Viewers' },
  { key: 'viewers.inventoryMovement', name: 'Inventory Movement Viewer', folder: 'Viewers' },
  { key: 'viewers.purchaseHistory', name: 'Purchase History Viewer', folder: 'Viewers' },
  { key: 'viewers.batchingOrder', name: 'Batching Order Viewer', folder: 'Viewers' },
  { key: 'viewers.whereUsed', name: 'Where Used Viewer', folder: 'Viewers' },
  { key: 'viewers.inventoryAtDate', name: 'Inventory At Date Viewer', folder: 'Viewers' },
  { key: 'viewers.completeMfOrders', name: 'Complete MF Orders Viewer', folder: 'Viewers' },
];

// Secured items = granular actions with a response level (reason / signature /
// witness). Created with sensible defaults; the require* flags are NOT reset on
// re-seed so operator tuning survives upgrades. Order completion requires an
// electronic signature + reason out of the box (witness optional).
const SECURED_ITEMS = [
  {
    key: 'order.complete',
    description: 'Sign-off on completing a batch order',
    requireReason: true,
    requireSignature: true,
    requireWitness: false,
  },
  {
    key: 'order.reverse',
    description: 'Sign-off on reversing a completed batch order (un-complete)',
    requireReason: true,
    requireSignature: true,
    requireWitness: false,
  },
  {
    key: 'order.revise',
    description: 'Sign-off on publishing a released-order revision (order edit)',
    // The mandatory revision comment is the narrative; no extra reason box.
    requireReason: false,
    requireSignature: true,
    requireWitness: false,
  },
  {
    key: 'release.disposition',
    description: 'Sign-off on a QA lot disposition (release / hold / reject)',
    requireReason: true,
    requireSignature: true,
    requireWitness: false,
  },
  {
    key: 'recipe.publish',
    description: 'Sign-off on publishing a batching or packaging recipe',
    requireReason: true,
    requireSignature: false,
    requireWitness: false,
  },
];

// Starter user groups (non-system roles) so the approval-policy editor has real
// groups to configure out of the box. Created if absent; never reset on re-seed.
// The operator can rename, re-scope (programs), or remove these later. ADMIN is
// seeded separately (system role).
const STARTER_ROLES = [
  { code: 'QA_MANAGER', name: 'QA Manager', description: 'Quality approvals (dispositions, releases).' },
  { code: 'SUPERVISOR', name: 'Supervisor', description: 'Production supervisor — approves orders & edits.' },
  { code: 'OPERATOR', name: 'Operator', description: 'Shop-floor operator — requests approval, does not approve.' },
];

// Default per-group approval policy (the six capabilities of the approval engine).
// Seeded create-only (operator tuning survives re-seed). A role WITHOUT a row
// falls back to the service default (request-only). Not yet enforced on any
// specific action — that trigger is wired separately.
const APPROVAL_POLICIES: Record<
  string,
  { canRequestApproval: boolean; canApprove: boolean; canApproveUpdate: boolean; canApproveChange: boolean; canOverride: boolean; noApprovalRequired: boolean }
> = {
  // Administrator is never blocked by an approval gate.
  ADMIN: { canRequestApproval: true, canApprove: true, canApproveUpdate: true, canApproveChange: true, canOverride: true, noApprovalRequired: true },
  QA_MANAGER: { canRequestApproval: true, canApprove: true, canApproveUpdate: true, canApproveChange: true, canOverride: true, noApprovalRequired: false },
  SUPERVISOR: { canRequestApproval: true, canApprove: true, canApproveUpdate: true, canApproveChange: true, canOverride: false, noApprovalRequired: false },
  OPERATOR: { canRequestApproval: true, canApprove: false, canApproveUpdate: false, canApproveChange: false, canOverride: false, noApprovalRequired: false },
};

// Default application settings (seeded only if absent — never overwrite an
// operator-changed value). Foundation for the Configuration module.
const DEFAULT_SETTINGS = [
  { key: 'company.name', value: 'Precision Ink Corporation', description: 'Company name shown on printed documents (batch tickets, labels, purchase orders).' },
  { key: 'company.phone', value: '847-952-1500', description: 'Company phone shown in the purchase-order footer.' },
  { key: 'company.email', value: 'PURCHASING@PRECISIONINKCORP.COM', description: 'Purchasing email shown in the purchase-order footer.' },
  { key: 'company.logoDataUrl', value: '', description: 'Company logo (data URL) printed in customer-facing document headers. Empty = text-only header.' },
  { key: 'batchSheet.gramsThresholdLb', value: '0.05', description: 'Batch-ticket quantities at or below this many pounds are shown in grams instead.' },
  { key: 'inventory.receivingLocation', value: '', description: 'Location code that received purchase stock lands in. Empty = auto-resolve the most-used inventory location.' },
  { key: 'inventory.productionLocation', value: '', description: 'Location code that finished-goods batch output lands in. Empty = auto-resolve the most-used inventory location.' },
  // Email notifications (UG ch.22). Delivery is OFF until an operator turns it
  // on — emitters always queue into EmailSent (free audit trail), the
  // processor only dispatches when enabled and SMTP is configured.
  { key: 'notifications.enabled', value: 'false', description: 'Master switch for e-mail notification DELIVERY. Rules always queue into the e-mail log; delivery only happens when this is true.' },
  { key: 'notifications.baseUrl', value: '', description: 'Public base URL of this ERP1 web app (e.g. https://erp1.example.com) used for deep links in notification e-mails. Empty = links rendered as plain text.' },
  { key: 'smtp.host', value: '', description: 'SMTP server host for outgoing notification e-mail. Empty = delivery disabled. The SMTP_URL environment variable overrides all smtp.* settings.' },
  { key: 'smtp.port', value: '587', description: 'SMTP server port (587 STARTTLS, 465 implicit TLS, 25 plain).' },
  { key: 'smtp.secure', value: 'false', description: 'true = implicit TLS from the first byte (port 465). false = plain or STARTTLS upgrade.' },
  { key: 'smtp.user', value: '', description: 'SMTP auth username. Empty = unauthenticated relay.' },
  { key: 'smtp.password', value: '', description: 'SMTP auth password. Prefer the SMTP_URL environment variable if you do not want the password stored in the database.' },
  { key: 'smtp.from', value: '', description: 'From address for notification e-mail, e.g. "ERP1 <erp1@example.com>". Empty = smtp.user.' },
  // Legacy ParamsInventory.ReweighThreshold (live value 5.0): an inventory
  // adjustment beyond this percentage of the container quantity fires the
  // "Reweigh Outside Threshold" notification.
  { key: 'inventory.reweighThreshold', value: '5', description: 'Percent variance on an inventory adjustment beyond which the Reweigh Outside Threshold notification fires. 0 disables the check.' },
  // §14 Configuration (legacy Params* live values where a counterpart exists;
  // full catalog + descriptions in apps/api/src/settings/settings-registry.ts).
  { key: 'batchExecution.yieldTolerancePercent', value: '5', description: 'Completion yield deviation (vs planned batch size) beyond this percent returns a warning. 0 disables.' },
  { key: 'receiving.manfLotRequired', value: 'true', description: 'Require a manufacturer lot number on every received lot (the recall key).' },
  { key: 'security.passwordMinLength', value: '12', description: 'Minimum password length enforced on password change (floor 6).' },
  { key: 'security.lockoutCount', value: '5', description: 'Consecutive failed logins before temporary lockout. 0 disables.' },
  { key: 'security.lockoutDurationMinutes', value: '15', description: 'How long a locked account stays locked.' },
  { key: 'sso.enabled', value: 'false', description: 'Master switch for OIDC SSO login. Effective only once issuer, client id and secret are configured.' },
  { key: 'sso.issuer', value: '', description: 'OIDC issuer (discovery) URL, e.g. https://login.microsoftonline.com/<tenant-id>/v2.0.' },
  { key: 'sso.clientId', value: '', description: 'Application (client) id registered with the identity provider.' },
  { key: 'sso.clientSecret', value: '', description: 'Client secret issued by the identity provider.' },
  { key: 'sso.buttonLabel', value: 'Sign in with SSO', description: 'Label of the SSO button on the login page.' },
  { key: 'accounting.arAccount', value: 'Accounts Receivable', description: 'External account debited by exported invoices.' },
  { key: 'accounting.apAccount', value: 'Accounts Payable', description: 'External account credited by exported purchase-receipt bills.' },
  { key: 'accounting.taxAccount1', value: 'Sales Tax Payable', description: 'Account credited with level-1 tax on exported invoices.' },
  { key: 'accounting.taxAccount2', value: 'Sales Tax Payable', description: 'Account credited with level-2 tax on exported invoices.' },
  { key: 'accounting.taxAccount3', value: 'Sales Tax Payable', description: 'Account credited with level-3 tax on exported invoices.' },
  { key: 'accounting.freightAccount', value: 'Freight Income', description: 'Account credited with freight lines on exported invoices.' },
  { key: 'accounting.fallbackAccount', value: 'Uncategorized', description: 'Account used (with a warning) when a GL mapping cannot resolve.' },
];

async function main() {
  const adminEmail = process.env.ADMIN_EMAIL ?? 'mcartwright@precisioninkcorp.com';
  const adminPassword = process.env.ADMIN_INITIAL_PASSWORD;
  // Auto-generated passwords force a change at first login; operator-chosen ones don't.
  const mustChange = (process.env.ADMIN_MUST_CHANGE_PASSWORD ?? 'true').toLowerCase() !== 'false';

  // Administrator role (system role — cannot be deleted via UI).
  const adminRole = await prisma.role.upsert({
    where: { code: 'ADMIN' },
    update: {},
    create: {
      code: 'ADMIN',
      name: 'Administrator',
      description: 'Full system access',
      isSystem: true,
    },
  });

  // Baseline programs, all granted to Administrator.
  for (const p of BASELINE_PROGRAMS) {
    const prog = await prisma.program.upsert({
      where: { key: p.key },
      update: { name: p.name, folder: p.folder },
      create: p,
    });
    await prisma.roleProgram.upsert({
      where: { roleId_programId: { roleId: adminRole.id, programId: prog.id } },
      update: { allow: true },
      create: { roleId: adminRole.id, programId: prog.id, allow: true },
    });
  }

  // Secured items — create with defaults; on re-seed only refresh the description
  // (preserve operator-tuned require* flags). Grant the Administrator role both
  // the action and the right to witness it.
  for (const si of SECURED_ITEMS) {
    const item = await prisma.securedItem.upsert({
      where: { key: si.key },
      update: { description: si.description },
      create: si,
    });
    await prisma.roleSecuredItem.upsert({
      where: { roleId_securedItemId: { roleId: adminRole.id, securedItemId: item.id } },
      update: { allow: true, allowWitness: true },
      create: { roleId: adminRole.id, securedItemId: item.id, allow: true, allowWitness: true },
    });
  }

  // Default settings — create if absent; never overwrite an operator-changed value.
  for (const s of DEFAULT_SETTINGS) {
    await prisma.appSetting.upsert({
      where: { key: s.key },
      update: { description: s.description },
      create: { key: s.key, value: s.value, description: s.description },
    });
  }

  // Starter user groups — create if absent; never reset name/description on
  // re-seed (operator may have re-purposed them). Non-system so they're editable.
  for (const r of STARTER_ROLES) {
    await prisma.role.upsert({
      where: { code: r.code },
      update: {},
      create: { code: r.code, name: r.name, description: r.description, isSystem: false },
    });
  }

  // Per-group approval policies — create-only so operator tuning survives upgrades.
  // (ADMIN was upserted above; the starter roles just above.)
  for (const [code, policy] of Object.entries(APPROVAL_POLICIES)) {
    const role = await prisma.role.findUnique({ where: { code }, select: { id: true } });
    if (!role) continue;
    await prisma.roleApprovalPolicy.upsert({
      where: { roleId: role.id },
      update: {},
      create: { roleId: role.id, ...policy },
    });
  }

  // Bootstrap admin user — create only if missing.
  const existing = await prisma.user.findUnique({ where: { email: adminEmail } });
  if (existing) {
    console.log(`[seed] Admin already exists (${adminEmail}); leaving unchanged.`);
    return;
  }

  if (!adminPassword) {
    throw new Error(
      '[seed] ADMIN_INITIAL_PASSWORD is not set; cannot create the bootstrap admin. ' +
        'The installer normally provides this.',
    );
  }

  const passwordHash = await hash(adminPassword, {
    // OWASP-recommended Argon2id parameters.
    memoryCost: 19456,
    timeCost: 2,
    parallelism: 1,
  });

  const admin = await prisma.user.create({
    data: {
      email: adminEmail,
      username: 'admin',
      displayName: 'Administrator',
      status: 'ACTIVE',
      passwordHash,
      mustChangePassword: mustChange,
      roles: { create: { roleId: adminRole.id } },
    },
  });

  console.log(`[seed] Created bootstrap admin: ${admin.email} (must change password on first login).`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (err) => {
    console.error(err);
    await prisma.$disconnect();
    process.exit(1);
  });
