// Idempotent database seed.
//
// - Creates the Administrator role and baseline programs.
// - Creates the bootstrap admin user ONLY if it does not already exist.
//   On upgrades (admin present) it changes nothing — credentials are never
//   reset by the seed. The initial password comes from ADMIN_INITIAL_PASSWORD
//   (generated by the installer) and the admin must change it on first login.

import { hash } from '@node-rs/argon2';
import { PrismaClient } from '../generated/client/index.js';

const prisma = new PrismaClient();

const BASELINE_PROGRAMS = [
  { key: 'dashboard', name: 'Dashboard', folder: 'File' },
  { key: 'admin.users', name: 'User Administration', folder: 'Administration' },
  { key: 'admin.roles', name: 'Role Administration', folder: 'Administration' },
  { key: 'admin.securedItems', name: 'Secured Items', folder: 'Administration' },
  { key: 'admin.audit', name: 'Audit Log', folder: 'Administration' },
  { key: 'admin.sessions', name: 'Active Sessions', folder: 'Administration' },
  { key: 'master.entities', name: 'Entities', folder: 'Master Tables' },
  { key: 'master.items', name: 'Items', folder: 'Master Tables' },
  { key: 'master.units', name: 'Units', folder: 'Master Tables' },
  { key: 'recipe.manager', name: 'Recipe Manager', folder: 'Master Tables/Recipe Manager' },
  { key: 'orders.browser', name: 'Order Browser', folder: 'Transactions/Orders' },
  { key: 'orders.create', name: 'Create Order', folder: 'Transactions/Orders' },
  { key: 'orders.edit', name: 'Edit Order', folder: 'Transactions/Orders' },
  { key: 'orders.release', name: 'Release Order', folder: 'Transactions/Orders' },
  { key: 'orders.complete', name: 'Complete Order', folder: 'Transactions/Orders' },
  { key: 'orders.close', name: 'Close Order', folder: 'Transactions/Orders' },
  { key: 'sales.invoices', name: 'Invoices', folder: 'Transactions/Sales' },
  { key: 'sales.shipments', name: 'Packing Slips', folder: 'Transactions/Sales' },
  { key: 'sales.bills', name: 'Supplier Bills', folder: 'Transactions/Purchasing' },
  { key: 'purchasing.po', name: 'Purchase Orders', folder: 'Transactions/Purchasing' },
  { key: 'purchasing.create', name: 'Create Purchase Order', folder: 'Transactions/Purchasing' },
  { key: 'purchasing.receive', name: 'Receive Purchase Order', folder: 'Transactions/Purchasing' },
  { key: 'qa.cofa', name: 'Certificates of Analysis', folder: 'Quality' },
  { key: 'qa.disposition', name: 'QA Disposition', folder: 'Quality' },
  { key: 'qa.results', name: 'Enter Test Results', folder: 'Quality' },
  { key: 'inventory.browser', name: 'Inventory Browser', folder: 'Transactions/Inventory' },
  { key: 'inventory.trace', name: 'Trace Genealogy', folder: 'Transactions/Inventory' },
  { key: 'inventory.recall', name: 'Recall', folder: 'Transactions/Inventory' },
  { key: 'admin.import', name: 'Legacy Import', folder: 'Administration' },
  { key: 'admin.config', name: 'Configuration', folder: 'Administration' },
];

// Secured items = granular actions with a response level (reason / signature /
// witness). Created with sensible defaults; the require* flags are NOT reset on
// re-seed so operator tuning survives upgrades. Order completion requires an
// electronic signature + reason out of the box (witness optional).
const SECURED_ITEMS = [
  {
    key: 'order.complete',
    description: 'Sign-off on completing a batch order',
    requireReason: true,
    requireSignature: true,
    requireWitness: false,
  },
  {
    key: 'release.disposition',
    description: 'Sign-off on a QA lot disposition (release / hold / reject)',
    requireReason: true,
    requireSignature: true,
    requireWitness: false,
  },
];

// Default application settings (seeded only if absent — never overwrite an
// operator-changed value). Foundation for the Configuration module.
const DEFAULT_SETTINGS = [
  { key: 'company.name', value: 'Precision Ink', description: 'Company name shown on printed documents (batch tickets, labels).' },
  { key: 'batchSheet.gramsThresholdLb', value: '0.05', description: 'Batch-ticket quantities at or below this many pounds are shown in grams instead.' },
];

async function main() {
  const adminEmail = process.env.ADMIN_EMAIL ?? 'mcartwright@precisioninkcorp.com';
  const adminPassword = process.env.ADMIN_INITIAL_PASSWORD;
  // Auto-generated passwords force a change at first login; operator-chosen ones don't.
  const mustChange = (process.env.ADMIN_MUST_CHANGE_PASSWORD ?? 'true').toLowerCase() !== 'false';

  // Administrator role (system role — cannot be deleted via UI).
  const adminRole = await prisma.role.upsert({
    where: { code: 'ADMIN' },
    update: {},
    create: {
      code: 'ADMIN',
      name: 'Administrator',
      description: 'Full system access',
      isSystem: true,
    },
  });

  // Baseline programs, all granted to Administrator.
  for (const p of BASELINE_PROGRAMS) {
    const prog = await prisma.program.upsert({
      where: { key: p.key },
      update: { name: p.name, folder: p.folder },
      create: p,
    });
    await prisma.roleProgram.upsert({
      where: { roleId_programId: { roleId: adminRole.id, programId: prog.id } },
      update: { allow: true },
      create: { roleId: adminRole.id, programId: prog.id, allow: true },
    });
  }

  // Secured items — create with defaults; on re-seed only refresh the description
  // (preserve operator-tuned require* flags). Grant the Administrator role both
  // the action and the right to witness it.
  for (const si of SECURED_ITEMS) {
    const item = await prisma.securedItem.upsert({
      where: { key: si.key },
      update: { description: si.description },
      create: si,
    });
    await prisma.roleSecuredItem.upsert({
      where: { roleId_securedItemId: { roleId: adminRole.id, securedItemId: item.id } },
      update: { allow: true, allowWitness: true },
      create: { roleId: adminRole.id, securedItemId: item.id, allow: true, allowWitness: true },
    });
  }

  // Default settings — create if absent; never overwrite an operator-changed value.
  for (const s of DEFAULT_SETTINGS) {
    await prisma.appSetting.upsert({
      where: { key: s.key },
      update: { description: s.description },
      create: { key: s.key, value: s.value, description: s.description },
    });
  }

  // Bootstrap admin user — create only if missing.
  const existing = await prisma.user.findUnique({ where: { email: adminEmail } });
  if (existing) {
    console.log(`[seed] Admin already exists (${adminEmail}); leaving unchanged.`);
    return;
  }

  if (!adminPassword) {
    throw new Error(
      '[seed] ADMIN_INITIAL_PASSWORD is not set; cannot create the bootstrap admin. ' +
        'The installer normally provides this.',
    );
  }

  const passwordHash = await hash(adminPassword, {
    // OWASP-recommended Argon2id parameters.
    memoryCost: 19456,
    timeCost: 2,
    parallelism: 1,
  });

  const admin = await prisma.user.create({
    data: {
      email: adminEmail,
      username: 'admin',
      displayName: 'Administrator',
      status: 'ACTIVE',
      passwordHash,
      mustChangePassword: mustChange,
      roles: { create: { roleId: adminRole.id } },
    },
  });

  console.log(`[seed] Created bootstrap admin: ${admin.email} (must change password on first login).`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (err) => {
    console.error(err);
    await prisma.$disconnect();
    process.exit(1);
  });
